services:
  - type: web
    name: dimension-composition-api
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kur9426_db_user:AtVOwEWXA1YhJrro@cluster0.nqndxh8.mongodb.net/dimension_composition?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: dimension_composition_secret_2026
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://dimensioncomposition.com
